### ISSUE TITLE
Load .xopp on Xournal, create pdf and delete xopp files. replace them with pdf

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Paper-Highlights#1]
@Sgsouham

**Comment by parmarsuraj99** [comment]
Should future papers also be in .pdf format rather than .xopp?

**Comment by ucalyptus** [comment]
.xopp creates a vendor lock-in situation. Most people have a non-linux / non-MacOS setup and thus this project would face huge incompatibility issues.
What this repo can rather do is something like https://github.com/BraneShop/showreel/issues/
